name: Build and push image

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
        description: 'The tags to build the images with. Written as a JSON array. Eg. ''["latest", "20240101120000"]'''
      image_name:
        required: false
        type: string
        description: 'The name of the image to build. If not provided, the repository name will be used.'
      component:
        required: true
        type: string
        description: 'The component to build (client or server)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up input name
        id: input-name
        run: |
          if [ -z "${{ inputs.image_name }}" ]; then
            echo "name=${{ github.repository }}-${{ inputs.component }}" >> $GITHUB_OUTPUT
          else
            echo "name=${{ github.repository_owner }}/${{ inputs.image_name }}-${{ inputs.component }}" >> $GITHUB_OUTPUT
          fi

      - name: Prepare tags
        id: prep
        run: |
          TAGS=""
          for tag in $(echo '${{ inputs.tags }}' | jq -r '.[]'); do
            if [ -n "$TAGS" ]; then
              TAGS="${TAGS},"
            fi
            TAGS="${TAGS}ghcr.io/${{ steps.input-name.outputs.name }}:${tag}"
          done
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.component }}
          tags: ${{ steps.prep.outputs.tags }}
          push: true
