name: Checks

on:
  push:
    branches: ['main']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build-client:
    uses: ./.github/workflows/build-image.yml
    with:
      timestamped_tag: true
      sha_tag: true
      latest_tag: true
      image_name: '5ddwmt'
      component: 'client'

  build-server:
    uses: ./.github/workflows/build-image.yml
    with:
      timestamped_tag: true
      sha_tag: true
      latest_tag: true
      image_name: '5ddwmt'
      component: 'server'
